# Generated by Django 5.2.9 on 2025-12-23 20:40

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom_complet', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('matricule', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Matricule')),
                ('statut_global', models.CharField(choices=[('etudiant', 'Étudiant'), ('alumni', 'Alumni'), ('enseignant', 'Enseignant'), ('personnel_admin', 'Personnel Administratif'), ('personnel_technique', 'Personnel Technique'), ('partenaire', 'Partenaire')], max_length=30, verbose_name='Statut global')),
                ('travailleur', models.BooleanField(default=False, verbose_name='Travailleur')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('pays', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Pays')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos_profils/', verbose_name='Photo de profil')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('annee_sortie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils', to='core.anneepromotion', verbose_name='Promotion')),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils', to='core.domaine', verbose_name='Domaine')),
                ('titre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils', to='core.titrehonorifique', verbose_name='Titre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'db_table': 'profil',
            },
        ),
        migrations.CreateModel(
            name='LienReseauSocialProfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('url', models.URLField(verbose_name='URL')),
                ('est_actif', models.BooleanField(default=True)),
                ('reseau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens', to='core.reseausocial', verbose_name='Réseau social')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_reseaux', to='users.profil')),
            ],
            options={
                'verbose_name': 'Lien de résseau social',
                'db_table': 'lien_reseau_social_profil',
            },
        ),
    ]
