# Generated by Django 5.2.9 on 2025-12-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='statut_global',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('alumni', 'Alumni'), ('enseignant', 'Enseignant'), ('personnel_admin', 'Personnel Administratif'), ('partenaire', 'Partenaire')], max_length=30, verbose_name='Statut global'),
        ),
    ]
