# Generated by Django 5.2.9 on 2025-12-28 20:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0002_alter_profil_statut_global'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='travailleur',
        ),
        migrations.CreateModel(
            name='ExperienceProfessionnelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('titre_poste', models.CharField(help_text='Ex: Ingénieur Logiciel, Consultant, Directeur Technique...', max_length=255, verbose_name='Titre du poste')),
                ('nom_entreprise', models.CharField(max_length=255, verbose_name='Entreprise ou Organisation')),
                ('lieu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu (Ville, Pays ou Distanciel)')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text='Laissez vide si vous occupez toujours ce poste', null=True, verbose_name='Date de fin')),
                ('est_poste_actuel', models.BooleanField(default=False, verbose_name='Poste actuel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Missions et réalisations')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences_liees', to='organizations.organisation', verbose_name='Lien avec une organisation du Hub')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='users.profil', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Expérience Professionnelle',
                'db_table': 'experience_professionnelle',
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['profil', '-date_debut'], name='experience__profil__d46ea6_idx'), models.Index(fields=['est_poste_actuel'], name='experience__est_pos_6f47af_idx')],
            },
        ),
    ]
