# Generated by Django 5.2.9 on 2026-01-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profil_travailleur_experienceprofessionnelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='nom_complet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom complet'),
        ),
    ]
