# Generated by Django 5.2.9 on 2025-12-12 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('mot_de_passe', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('role_systeme', models.CharField(choices=[('user', 'Utilisateur'), ('admin_site', 'Administrateur site'), ('super_admin', 'Super Administrateur')], default='user', max_length=20, verbose_name='Rôle système')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès admin Django')),
                ('groups', models.ManyToManyField(blank=True, related_name='ensp_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='ensp_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('ACCESS_DENIED', 'Access denied')], db_index=True, max_length=20, verbose_name='Action')),
                ('entity_type', models.CharField(db_index=True, max_length=100, verbose_name="Type d'entité")),
                ('entity_id', models.UUIDField(db_index=True, verbose_name="ID de l'entité")),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Anciennes valeurs')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Nouvelles valeurs')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom_complet', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matricule')),
                ('titre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Titre (Dr., Prof., etc.)')),
                ('statut_global', models.CharField(choices=[('etudiant', 'Étudiant'), ('alumni', 'Alumni'), ('enseignant', 'Enseignant'), ('personnel_admin', 'Personnel Administratif'), ('personnel_technique', 'Personnel Technique'), ('partenaire', 'Partenaire')], max_length=30, verbose_name='Statut global')),
                ('travailleur', models.BooleanField(default=False, verbose_name='Travailleur')),
                ('annee_sortie', models.SmallIntegerField(blank=True, null=True, verbose_name='Année de sortie')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos_profils/', verbose_name='Photo de profil')),
                ('domaine', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domaine')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'db_table': 'profil',
            },
        ),
        migrations.CreateModel(
            name='LienReseauSocial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom_reseau', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('GitHub', 'GitHub'), ('ResearchGate', 'ResearchGate'), ('GoogleScholar', 'Google Scholar'), ('SiteWeb', 'Site Web'), ('Portfolio', 'Portfolio')], max_length=50)),
                ('url', models.URLField(verbose_name='URL')),
                ('est_actif', models.BooleanField(default=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_reseaux', to='core.profil')),
            ],
            options={
                'verbose_name': 'Lien réseau social',
                'db_table': 'lien_reseau_social',
            },
        ),
    ]
