# Generated by Django 5.2.9 on 2025-12-07 05:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, null=True, verbose_name="Prenon de l'utilisateur")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matricule')),
                ('statut', models.CharField(choices=[('etudiant', 'Étudiant'), ('enseignant', 'Enseignant'), ('directeur', 'Directeur'), ('partenaire', 'Partenaire'), ('personnel_admin', 'Personnel Administratif'), ('personnel_technique', 'Personnel Technique')], max_length=50, verbose_name='Statut')),
                ('titre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Titre (ex: Ing., Dr.)')),
                ('travailleur', models.BooleanField(default=False, verbose_name='Est travailleur')),
                ('annee_sortie', models.SmallIntegerField(blank=True, null=True, verbose_name='Année de sortie')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('bio', models.TextField(blank=True, null=True, verbose_name="Description sur l'utilisateur")),
                ('photo_profile', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('domaine', models.CharField(blank=True, max_length=100, null=True, verbose_name="Domaine d'étude")),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('admin', 'Administrateur'), ('super_admin', 'Super Administrateur')], default='user', max_length=20, verbose_name='Rôle système')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès admin Django')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'user',
            },
        ),
    ]
