# Generated by Django 5.2.9 on 2025-12-24 16:47

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='new_values',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Nouvelles valeurs'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_values',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Anciennes valeurs'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='synonymes',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="Liste des variantes: ['Dev', 'Développeur', 'Software Engineer']", verbose_name='Synonymes'),
        ),
    ]
