# Generated by Django 5.2.9 on 2025-12-28 20:07

import core.utils.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_new_values_alter_auditlog_old_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='new_values',
            field=models.JSONField(blank=True, encoder=core.utils.encoder.CountriesEncoder, null=True, verbose_name='Nouvelles valeurs'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_values',
            field=models.JSONField(blank=True, encoder=core.utils.encoder.CountriesEncoder, null=True, verbose_name='Anciennes valeurs'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='synonymes',
            field=models.JSONField(blank=True, default=list, encoder=core.utils.encoder.CountriesEncoder, help_text="Liste des variantes: ['Dev', 'Développeur', 'Software Engineer']", verbose_name='Synonymes'),
        ),
    ]
