# Generated by Django 5.2.9 on 2026-01-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_passwordresettoken'),
        ('organizations', '0002_remove_membreorganisation_poste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poste',
        ),
    ]
