# Generated by Django 5.2.9 on 2025-12-12 21:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom_organisation', models.CharField(max_length=255)),
                ('type_organisation', models.CharField(choices=[('entreprise', 'Entreprise'), ('ong', 'ONG'), ('institution_publique', 'Institution publique'), ('startup', 'Startup'), ('universite', 'Université'), ('gouvernement', 'Gouvernement'), ('autre', 'Autre'), ('association', 'Association')], max_length=30)),
                ('secteur_activite', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('email_general', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone_general', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_organisations/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('en_attente', 'En attente')], default='en_attente', max_length=20)),
            ],
            options={
                'verbose_name': 'Organisation',
                'db_table': 'organisation',
            },
        ),
        migrations.CreateModel(
            name='MembreOrganisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('role_organisation', models.CharField(choices=[('employe', 'Employé'), ('administrateur_page', 'Administrateur page')], default='employe', max_length=30)),
                ('poste', models.CharField(blank=True, max_length=150, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_joindre', models.DateField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_organisations', to='core.profil')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='organizations.organisation')),
            ],
            options={
                'verbose_name': 'Membre organisation',
                'db_table': 'membre_organisation',
                'unique_together': {('profil', 'organisation', 'est_actif')},
            },
        ),
        migrations.CreateModel(
            name='AbonnementOrganisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('date_abonnement', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='core.profil')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnés', to='organizations.organisation')),
            ],
            options={
                'verbose_name': 'Abonnement organisation',
                'db_table': 'abonnement_organisation',
                'unique_together': {('profil', 'organisation')},
            },
        ),
    ]
