# Generated by Django 5.2.9 on 2025-12-21 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom_organisation', models.CharField(max_length=255, verbose_name="Nom de l'organisation")),
                ('slug', models.SlugField(blank=True, help_text='Identifiant unique pour les URLs (ex: ensp-maroua-x7r2p9)', null=True, unique=True, verbose_name='Slug')),
                ('type_organisation', models.CharField(choices=[('entreprise', 'Entreprise'), ('ong', 'ONG'), ('institution_publique', 'Institution publique'), ('startup', 'Startup'), ('universite', 'Université'), ('gouvernement', 'Gouvernement'), ('autre', 'Autre'), ('association', 'Association')], max_length=30, verbose_name="Type d'organisation")),
                ('secteur_activite', models.CharField(blank=True, max_length=150, null=True, verbose_name="Secteur d'activité")),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('pays', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('email_general', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email général')),
                ('telephone_general', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone général')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_organisations/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name="Date de création de l'organisation")),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('en_attente', 'En attente')], default='en_attente', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table': 'organisation',
                'ordering': ['nom_organisation'],
            },
        ),
        migrations.CreateModel(
            name='MembreOrganisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('role_organisation', models.CharField(choices=[('employe', 'Employé'), ('administrateur_page', 'Administrateur page')], default='employe', max_length=30, verbose_name="Rôle dans l'organisation")),
                ('poste', models.CharField(blank=True, max_length=150, null=True, verbose_name='Poste')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Membre actif')),
                ('date_joindre', models.DateField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_organisations', to='core.profil', verbose_name='Profil')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='organizations.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Membre organisation',
                'verbose_name_plural': 'Membres organisations',
                'db_table': 'membre_organisation',
                'ordering': ['profil__nom_complet'],
                'unique_together': {('profil', 'organisation', 'est_actif')},
            },
        ),
        migrations.CreateModel(
            name='AbonnementOrganisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('date_abonnement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'abonnement")),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='core.profil', verbose_name='Profil')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnes', to='organizations.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Abonnement organisation',
                'verbose_name_plural': 'Abonnements organisations',
                'db_table': 'abonnement_organisation',
                'ordering': ['-date_abonnement'],
                'unique_together': {('profil', 'organisation')},
            },
        ),
    ]
