# Generated by Django 5.2.9 on 2026-01-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membreorganisation',
            name='poste',
        ),
    ]
