# Generated by Django 5.2.9 on 2025-12-21 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom_groupe', models.CharField(max_length=150, unique=True)),
                ('photo_groupe', models.ImageField(blank=True, null=True, upload_to='photos_groups/')),
                ('description', models.TextField()),
                ('est_valide', models.BooleanField(default=False)),
                ('type_groupe', models.CharField(choices=[('public', 'Public'), ('prive', 'Privé'), ('administratif', 'Administratif')], default='prive', max_length=20)),
                ('max_membres', models.PositiveIntegerField(blank=True, null=True)),
                ('createur_profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_crees', to='core.profil')),
            ],
            options={
                'db_table': 'groupe',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('texte', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='messages_fichier/')),
                ('type_fichier', models.CharField(blank=True, choices=[('image', 'Image'), ('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('video', 'Vidéo')], max_length=20, null=True)),
                ('est_supprime', models.BooleanField(default=False)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.groupe')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profil')),
            ],
            options={
                'db_table': 'message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationGroupe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('est_approuve', models.BooleanField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='chat.groupe')),
                ('validateur_profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profil')),
            ],
            options={
                'db_table': 'validation_groupe',
            },
        ),
        migrations.CreateModel(
            name='MembreGroupe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('role_membre', models.CharField(choices=[('membre', 'Membre'), ('moderateur', 'Modérateur'), ('admin', 'Admin')], default='membre', max_length=20)),
                ('date_adhesion', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='chat.groupe')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profil')),
            ],
            options={
                'db_table': 'membre_groupe',
                'unique_together': {('profil', 'groupe')},
            },
        ),
    ]
