# Generated by Django 5.2.9 on 2025-12-12 21:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('lien_inscription', models.URLField(blank=True, null=True)),
                ('organisateur_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_organises', to='organizations.organisation')),
                ('organisateur_profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_organises', to='core.profil')),
            ],
            options={
                'verbose_name': 'Événement',
                'db_table': 'evenement',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts_images/')),
                ('nombre_likes', models.PositiveIntegerField(default=0)),
                ('auteur_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='organizations.organisation')),
                ('auteur_profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.profil')),
            ],
            options={
                'verbose_name': 'Post',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('contenu', models.TextField()),
                ('auteur_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organisation')),
                ('auteur_profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profil')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='feeds.post')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'db_table': 'commentaire',
            },
        ),
    ]
