# Generated by Django 5.2.9 on 2025-12-21 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('feeds', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='auteur_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organisation'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='auteur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profil'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='organisateur_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_organises', to='organizations.organisation'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='organisateur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_organises', to='core.profil'),
        ),
        migrations.AddField(
            model_name='post',
            name='auteur_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='organizations.organisation'),
        ),
        migrations.AddField(
            model_name='post',
            name='auteur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.profil'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='feeds.post'),
        ),
    ]
