# Generated by Django 5.2.9 on 2025-12-12 21:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('titre', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=150)),
                ('nom_structure', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_emploi', models.CharField(blank=True, choices=[('temps_plein_terrain', 'Temps plein terrain'), ('temps_partiel_terrain', 'Temps partiel terrain'), ('temps_plein_ligne', 'Temps plein ligne')], max_length=40, null=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('lien_offre_original', models.URLField(blank=True, null=True)),
                ('lien_candidature', models.URLField(blank=True, null=True)),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expirée'), ('pourvue', 'Pourvue')], default='active', max_length=20)),
                ('createur_profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profil')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organisation')),
            ],
            options={
                'db_table': 'emploi',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('titre', models.CharField(max_length=255)),
                ('lieu', models.CharField(blank=True, max_length=150, null=True)),
                ('nom_structure', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_formation', models.CharField(choices=[('en_ligne', 'En ligne'), ('presentiel', 'Présentiel'), ('hybride', 'Hybride')], max_length=20)),
                ('est_payante', models.BooleanField(default=False)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('lien_formation', models.URLField(blank=True, null=True)),
                ('lien_inscription', models.URLField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('devise', models.CharField(default='XAF', max_length=10)),
                ('est_valide', models.BooleanField(default=False)),
                ('createur_profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profil')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organisation')),
            ],
            options={
                'db_table': 'formation',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('titre', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=150)),
                ('nom_structure', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_stage', models.CharField(choices=[('ouvrier', 'Ouvrier'), ('academique', 'Académique'), ('professionnel', 'Professionnel')], max_length=20)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('lien_offre_original', models.URLField(blank=True, null=True)),
                ('lien_candidature', models.URLField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expirée'), ('pourvue', 'Pourvue')], default='active', max_length=20)),
                ('createur_profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profil')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organisation')),
            ],
            options={
                'db_table': 'stage',
            },
        ),
        migrations.CreateModel(
            name='ValidationFormation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('est_approuve', models.BooleanField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='opportunities.formation')),
                ('validateur_profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profil')),
            ],
            options={
                'db_table': 'validation_formation',
            },
        ),
    ]
