# Generated by Django 5.2.9 on 2025-12-21 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('opportunities', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploi',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organisation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='createur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profil'),
        ),
        migrations.AddField(
            model_name='formation',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organisation'),
        ),
        migrations.AddField(
            model_name='stage',
            name='createur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profil'),
        ),
        migrations.AddField(
            model_name='stage',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organisation'),
        ),
        migrations.AddField(
            model_name='validationformation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='opportunities.formation'),
        ),
        migrations.AddField(
            model_name='validationformation',
            name='validateur_profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profil'),
        ),
    ]
