# Generated by Django 5.2.9 on 2025-12-21 13:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('opportunities', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emploi',
            options={'ordering': ['-date_publication'], 'verbose_name': 'Emploi', 'verbose_name_plural': 'Emplois'},
        ),
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['-date_publication'], 'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['-date_publication'], 'verbose_name': 'Stage', 'verbose_name_plural': 'Stages'},
        ),
        migrations.AddField(
            model_name='emploi',
            name='commentaire_validation',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire de validation'),
        ),
        migrations.AddField(
            model_name='emploi',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='emploi',
            name='devise',
            field=models.CharField(default='XAF', max_length=10, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='emploi',
            name='est_valide',
            field=models.BooleanField(default=False, verbose_name='Validé'),
        ),
        migrations.AddField(
            model_name='emploi',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='emploi',
            name='salaire_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire maximum'),
        ),
        migrations.AddField(
            model_name='emploi',
            name='salaire_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire minimum'),
        ),
        migrations.AddField(
            model_name='emploi',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='emploi',
            name='validateur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_valides', to='core.profil', verbose_name='Validateur'),
        ),
        migrations.AddField(
            model_name='emploi',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='formation',
            name='commentaire_validation',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire de validation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de publication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='duree_heures',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée en heures'),
        ),
        migrations.AddField(
            model_name='formation',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='formation',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='formation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('active', 'Active'), ('expiree', 'Expirée'), ('annulee', 'Annulée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='formation',
            name='validateur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_validees', to='core.profil', verbose_name='Validateur'),
        ),
        migrations.AddField(
            model_name='formation',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='stage',
            name='commentaire_validation',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire de validation'),
        ),
        migrations.AddField(
            model_name='stage',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de publication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='stage',
            name='est_valide',
            field=models.BooleanField(default=False, verbose_name='Validé'),
        ),
        migrations.AddField(
            model_name='stage',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='stage',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identifiant unique pour les URLs', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='stage',
            name='validateur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_valides', to='core.profil', verbose_name='Validateur'),
        ),
        migrations.AddField(
            model_name='stage',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='createur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_crees', to='core.profil', verbose_name='Créateur'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='lien_candidature',
            field=models.URLField(blank=True, null=True, verbose_name='Lien candidature'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='lien_offre_original',
            field=models.URLField(blank=True, null=True, verbose_name='Lien offre originale'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='lieu',
            field=models.CharField(max_length=150, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='nom_structure',
            field=models.CharField(max_length=255, verbose_name='Nom de la structure'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois', to='organizations.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('active', 'Active'), ('expiree', 'Expirée'), ('pourvue', 'Pourvue'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='telephone_contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre du poste'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='type_emploi',
            field=models.CharField(blank=True, choices=[('temps_plein_terrain', 'Temps plein terrain'), ('temps_partiel_terrain', 'Temps partiel terrain'), ('temps_plein_ligne', 'Temps plein en ligne'), ('temps_partiel_ligne', 'Temps partiel en ligne'), ('freelance', 'Freelance'), ('contrat', 'Contrat')], max_length=40, null=True, verbose_name="Type d'emploi"),
        ),
        migrations.AlterField(
            model_name='formation',
            name='createur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_creees', to='core.profil', verbose_name='Créateur'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='devise',
            field=models.CharField(default='XAF', max_length=10, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='est_payante',
            field=models.BooleanField(default=False, verbose_name='Formation payante'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='est_valide',
            field=models.BooleanField(default=False, verbose_name='Validé'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='lien_formation',
            field=models.URLField(blank=True, null=True, verbose_name='Lien de la formation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='lien_inscription',
            field=models.URLField(blank=True, null=True, verbose_name="Lien d'inscription"),
        ),
        migrations.AlterField(
            model_name='formation',
            name='lieu',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='nom_structure',
            field=models.CharField(max_length=255, verbose_name='Nom de la structure'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='organizations.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='telephone_contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre de la formation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='type_formation',
            field=models.CharField(choices=[('en_ligne', 'En ligne'), ('presentiel', 'Présentiel'), ('hybride', 'Hybride')], max_length=20, verbose_name='Type de formation'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='createur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_crees', to='core.profil', verbose_name='Créateur'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='lien_candidature',
            field=models.URLField(blank=True, null=True, verbose_name='Lien candidature'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='lien_offre_original',
            field=models.URLField(blank=True, null=True, verbose_name='Lien offre originale'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='lieu',
            field=models.CharField(max_length=150, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='nom_structure',
            field=models.CharField(max_length=255, verbose_name='Nom de la structure'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='organizations.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('active', 'Active'), ('expiree', 'Expirée'), ('pourvue', 'Pourvue'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='telephone_contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre du stage'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type_stage',
            field=models.CharField(choices=[('ouvrier', 'Ouvrier'), ('academique', 'Académique'), ('professionnel', 'Professionnel')], max_length=20, verbose_name='Type de stage'),
        ),
        migrations.DeleteModel(
            name='ValidationFormation',
        ),
    ]
